### ISSUE TITLE
Cotización del BCP

### ISSUE THREAD

**Issue by nelruk** [aVolpe/cotizacion#34]
Muchas empresas usan el precio referencial del BCP, dado que los contables se manejan más en dicho precio que en el de las casas.
Esta es una sugerencia extraída del grupo de Python en Telegram
El link en cuestión: https://www.bcp.gov.py/webapps/web/cotizacion/monedas

**Comment by aVolpe** [comment]
En este PR https://github.com/aVolpe/cotizacion/pull/35 se agrega el cambio, deberia estar para hoy a la noche si el proceso de CI/CD no falla.

**Comment by aVolpe** [comment]
@nelruk podrias verificar si la solución es la adecuada?

Se ve así:

![Uploading image.png…]()
