### ISSUE TITLE
Solicitud para agregar Mercosur Cambios

### ISSUE THREAD

**Issue by danielmaldonado1708** [aVolpe/cotizacion#55]
Si es posible estaría genial que agregues la casa de cambios https://site.mercosurcambios.com/
Gracias de antemano

**Comment by aVolpe** [comment]
@danielmaldonado1708 sabes si tiene un API? o hay que scrapear su web? Veo que tiene una app, capaz tenga una api.

**Comment by aVolpe** [comment]
@danielmaldonado1708 se agrego cambios mercosur, podrias verificar si cumple con lo esperado?

**Comment by danielmaldonado1708** [comment]
💪muchas gracias! disculpa por haber desaparecido aquella vez
