### ISSUE TITLE
Dirección Cambios de Banco GNB

### ISSUE THREAD

**Issue by Armis128** [aVolpe/cotizacion#75]
Buenas, la dirección de la cual se obtiene los cambios ya no es la que se encuentra en la api "https://www.bancognb.com.py/Yaguarete/public/quotations", tengo entendido que la dirección actual es "https://www.bancognb.com.py/public/currency_quotations"
atentamente,

**Comment by aVolpe** [comment]
Gracias @Armis128 prepare este PR para corregir el problema: https://github.com/aVolpe/cotizacion/pull/76/files
